apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: database
spec:
  accessModes:
    - ReadWriteOnce # O volume pode ser montado para leitura/escrita por um único nó
  resources:
    requests:
      storage: 5Gi  
